### ISSUE TITLE
AttributeError: type object 'OverlayList' has no attribute 'AtlasPanel_140482816957744'

### ISSUE THREAD

**Issue by jaguarxp82** [pauldmccarthy/fsleyes-props#2]
Using FSL 6.0.5, when I open FSLeyes, and try overlay an atlas on a standard space "MNI_*". I get this error which I assume that it is due to incompatible versions of fsleyes and fsleyes_props. It is worth noting that in older versions, it was working fine.

![fsleyes_HL](https://user-images.githubusercontent.com/15674955/200916213-1c45ab42-a260-4a8a-81b9-056bd8ef1561.png)
![error](https://user-images.githubusercontent.com/15674955/200916217-8f073bb4-27b4-481b-a2b4-7d85db173c9e.png)

**Comment by pauldmccarthy** [comment]
See https://github.com/pauldmccarthy/fsleyes/issues/102#issuecomment-1310099607
